### ISSUE TITLE
attempt to set ngx.header.HEADER after sending out response headers

### ISSUE THREAD

**Issue by Rming** [Etiene/sailor#41]
```
2015/06/15 15:46:19 [error] 5380#0: *1 attempt to set ngx.header.HEADER after sending out response headers, client: 10.0.2.2, server: file.proxy.dev, request: "GET /index.lua HTTP/1.1", host: "file.proxy.dev"
```

ngx_openresty-1.7.10.1 + LuaJIT 2.1.0-alpha + sailor 0.3

It seems that er nginx and sailor have set HTTP HEADER.
There are also some problems working with nginx rewrite rules because of my poor knowledge .
I'm a beginner for the framework with little lua practice , it looks graceful.
FYI.

**Comment by Etiene** [comment]
Thank you! Gonna take a look at that as soon as possible :)

**Comment by njentit** [comment]
Found this code inside remy/nginx.lua M.finish causing mod_lua to print those error. My work arround is moving those code inside M.init to make default content type match requested
```lua
if request.content_type ~= nil then
ngx.header.content_type = request.content_type
end
```

**Comment by felipedaragon** [comment]
Hello. The code was originally written for nginx 1.5 with ngx_lua, so it may need small changes to work with ngx_openresty-1.7.10.1 + LuaJIT.

**Comment by Rming** [comment]
http://wiki.nginx.org/HttpLuaModule#lua_use_default_type
FYI.

I'll read the code of the framework lately

**Comment by felipedaragon** [comment]
Reproduced with: 1.7.10.1 and 1.5. The error was in the error.log even from version 1.5 but I failed to notice it. A fix is already in the master repo. Thx for reporting!
