### ISSUE TITLE
Sailor + SQLite3

### ISSUE THREAD

**Issue by amonaco** [Etiene/sailor#49]
Thanks for this cool framework!

We're planning to use Sailor for an embedded project, which makes a lot of sense. Also given the embedded nature of our needs, we are going to use SQLite3 as a persistence database. Is there any documentation where I can find the way to setup a SQLite3 database?

Thanks!

**Comment by Etiene** [comment]
Hello! Sorry for the delay on answering...
Try these steps:
1 - luarocks install luasql-sqlite3
2 - in the conf.lua of your app change the db driver to sqlite3 and the dbname to the path of your sqlite db file

**Comment by Etiene** [comment]
Timeout closing! Hope everything went well :)
